### PR TITLE
DNAstack's Data Connect URL updates

### PR DESCRIPTION
**Pull request by shiroyuki**
This PR is to replace all references to the decommissioned Data Connect service (`ga4gh-search-presto-adapter-public.prod.dnastack.com`) and the soon-to-be-decommissioned Data Connect service (`data-connect-trino-public.prod.dnastack.com`). The new hostname is `publisher-data.prod.dnastack.com`.

Please be aware that all tables in the queries for the Data Connect services will be updated as well.

### CODE REVIEW

**Review by jb-adams — APPROVED** [review]

**Comment by jb-adams** [comment]
hi @ianfore , this PR updates a notebook that was access data through our historical public data connect trino. We're decommissioning those services, so the notebook has been updated to use the equivalent services/datasets on our live platform.

Is there any process for getting this PR reviewed, or are we free to merge?

**Comment by jb-adams** [comment]
@ianfore @briandoconnor bumping this thread. Is there any process we need to follow for getting this PR merged?

**Comment by mbarkley** [comment]
@briandoconnor @ianfore If there are no objections, I will merge this PR at the end of this week.

**Comment by ianfore** [comment]
Thanks @mbarkley @jb-adams @shiroyuki . 
Comment as for https://github.com/ga4gh/Get-Started-with-GA4GH-APIs/pull/43

**Pull request merged**
